server:
  port: 8085

spring:
  application:
    name: justification-service

  datasource:
    url: jdbc:postgresql://localhost:5433/attendance_db
    #    url: jdbc:postgresql://attendance-db:5432/attendance_db
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
